public enum Sound {
    PLAYER_STEP,
    DOOR_OPEN,
    MENU_AMBIENT,
    GAME_AMBIENT,

    HEARTBEAT_SLOW,
    HEARTBEAT_FAST,

    UNDEAD_KING_1,
    UNDEAD_KING_2,
    UNDEAD_KING_3,
    UNDEAD_KING_4,
    UNDEAD_KING_5,
    UNDEAD_KING_6,
    UNDEAD_KING_7,
    UNDEAD_KING_8,
    UNDEAD_KING_9,
    UNDEAD_KING_10,
    UNDEAD_KING_DIE,
    UNDAED_KING_FIRE,

    EYE_1,
    EYE_2,
    EYE_DIED,
    EYE_FIRE
}
